### ISSUE TITLE
Porting to C++

### ISSUE THREAD

**Issue by 1over137** [adbar/simplemma#10]
This seems like a relatively simple library since I imagine most of the work is done on the data collection part. Would you consider porting it to C++ (and possibly other languages) so it can be more easily integrated to user applications?

**Comment by adbar** [comment]
Hi @1over137, yes I could consider it but I lack the time at the moment.

**Comment by adbar** [comment]
Hi @1over137, I added type annotations and mypy checks in 28f4487a91216bfd686d3b14af428082e7314fc9 & 94f1bfbf47d3331e6055d3b971353f32c491bb7a, so in principle it is be doable to pre-compile the package using [mypyc](https://github.com/mypyc/mypyc).

**Comment by adbar** [comment]
In fact a transcompiler/transpiler may be more adapted, now that the code is type-checked:
- see [transpiler topic](https://github.com/topics/transpiler)
- or software such as [py2many](https://github.com/py2many/py2many)
