### ISSUE TITLE
Setup: issue with packaging of dictionary data

### ISSUE THREAD

**Issue by adbar** [adbar/simplemma#100]
If I try to import the `lemmatize` function outside of simplemma's main directory I see the following error which has to do with the relative imports in the newly introduced classes.

@juanjoDiaz Could you please have a look at it?

```
   …
    from simplemma import lemmatize
  File "/home/adbar/.local/lib/python3.10/site-packages/simplemma/__init__.py", line 20, in <module>
    from .language_detector import LanguageDetector, in_target_language, langdetect
  File "/home/adbar/.local/lib/python3.10/site-packages/simplemma/language_detector.py", line 15, in <module>
    from .strategies import LemmatizationStrategy, DefaultStrategy
  File "/home/adbar/.local/lib/python3.10/site-packages/simplemma/strategies/__init__.py", line 3, in <module>
    from .dictionaries import DictionaryFactory, DefaultDictionaryFactory
  File "/home/adbar/.local/lib/python3.10/site-packages/simplemma/strategies/dictionaries/__init__.py", line 3, in <module>
    from .dictionary_factory import DictionaryFactory, DefaultDictionaryFactory
  File "/home/adbar/.local/lib/python3.10/site-packages/simplemma/strategies/dictionaries/dictionary_factory.py", line 30, in <module>
    for dict in listdir(DATA_FOLDER)
FileNotFoundError: [Errno 2] No such file or directory: '/home/adbar/.local/lib/python3.10/site-packages/simplemma/strategies/dictionaries/data'
```

**Comment by juanjoDiaz** [comment]
Can you give me some details of how are you getting this so I can reproduce it?

**Comment by adbar** [comment]
1. Go to any directory that is not `simplemma`'s home, e.g. `cd ~/` (one's home directory) or `cd tests/`
2. `python3` (interactive console or script)
3. `from simplemma import lemmatize`

**Comment by juanjoDiaz** [comment]
I don't understand 😅

If you don't have the package installed globally and you are not in the package folder.
How can you Python know where to find the `simplemma` module if you don't give it a full path?

**Comment by osma** [comment]
@juanjoDiaz I suppose @adbar had it installed using something like `pip install -e .` 
Based on the error message, Python can find the `simplemma` module just fine, but the simplemma code cannot find a specific directory:

    FileNotFoundError: [Errno 2] No such file or directory: '/home/adbar/.local/lib/python3.10/site-packages/simplemma/strategies/dictionaries/data'

**Comment by adbar** [comment]
Thanks @osma, I think that's the issue. It used to work with a local installation but it doesn't have to, I just need to change the installation mode.

Let's keep the issue open for now, I'll test using the package repo as source for pip and close the thread if it works.

**Comment by adbar** [comment]
I still don't understand however, this problem is new to me:
1. Using the master branch of the repository, I generate an experimental package version (say `0.9.1b0`): `python3 setup.py sdist bdist_wheel`
2. I install the corresponding package from source:  `pip3 install --force-reinstall dist/simplemma-0.9.1b0.tar.gz`
3. I still get the error with the relative paths, do you have an explanation?

**Comment by adbar** [comment]
There is something wrong with the directory where the dictionaries are installed, that's why they are not found:
- expected in `/home/adbar/.local/lib/python3.10/site-packages/simplemma/strategies/dictionaries/data/`
- present in `/home/adbar/.local/lib/python3.10/site-packages/simplemma/data/`

The dictionary folder is present but there is no `data/` folder. So it's a problem during package generation.

**Comment by adbar** [comment]
The `setup.py` file comprises this line which is now erroneous if I'm not mistaken:
`package_data={"simplemma": ["data/*.plzma"]}`
This should be another directory instead.

**Comment by osma** [comment]
I think the problem could be solved by using [importlib.resources](https://docs.python.org/3/library/importlib.resources.html) instead of accessing the data directory via `__file__` here: https://github.com/adbar/simplemma/blob/1cd7205ef1391d05d5f4b89923ed878daf85af6b/simplemma/strategies/dictionaries/dictionary_factory.py#L27

For some background and guidance, see these SO questions:

- [How to read a (static) file from inside a Python package?](https://stackoverflow.com/questions/6028000/how-to-read-a-static-file-from-inside-a-python-package)
- [Why use importlib.resources over `__file__`?](https://stackoverflow.com/questions/72886257/why-use-importlib-resources-over-file)
