### ISSUE TITLE
Document how simplemma's quality is assessed

### ISSUE THREAD

**Issue by juanjoDiaz** [adbar/simplemma#103]
So anyone building new strategies, modifying existing ones, using custom dictionaries, etc. can validate if he is improving or worsening simplemma.

**Comment by adbar** [comment]
It's [in the Readme](https://github.com/adbar/simplemma#supported-languages) (below the table) and the corresponding script is available in `training/eval/` (we need to change this in the Readme before the release). You should be able to reproduce the evaluation, does it work for you?

**Comment by juanjoDiaz** [comment]
Do you have any automated way to download the treebank files?
Or do you manually decompress the UD zip file and copy the relevant conllu files to the `eval/test` folder?

**Comment by adbar** [comment]
I added instructions: https://github.com/adbar/simplemma/blob/f49de0815ec2e49be38b465b4dbf9d48a9ae7170/eval/README.rst

Can you make sense of it and does it answer your question?

There were a few bugs so I needed to adapt the evaluation script. I also chose to move it for clarity.

My first observations are that the legacy `lemmatize()` function is much slower (around 2x), I'll run more checks.
