### ISSUE TITLE
Cyclic imports in `simplemma.strategies.dictionaries` 

### ISSUE THREAD

**Issue by adbar** [adbar/simplemma#145]
The new `trie_directory_factory` file seems to create cyclic imports as the dictionary strategies import each other (?) – source: pylint.

This is not a problem in itself but could make bugs difficult to find or to trace.

@juanjoDiaz if you want to have a look go ahead.

**Comment by juanjoDiaz** [comment]
The problem is the implementation of the `TrieDictionaryFactory` importing `from simplemma import __version__ as SIMPLEMMA_VERSION` which si used to cache.

As you know, I'm against the current caching model.
I think that we should cache locally, or should let the user decide where to cache.
Then we remove the dependency on `platformdirs`, avoid the existing issue and give the user full control.

Other option is to hardcode there the version but we need to remember to update it on every release.

You tell me what you prefer.

**Comment by juanjoDiaz** [comment]
The problem I see with that is that it will pick the simplemma version that you have installed with pip.
Not the version that you are working on at that moment. E.g., if you are developing 1.2.0 but have 1.1.0 installed.

**Comment by adbar** [comment]
This is tricky but if it's just for development you could change the version number and re-install the package locally?

@Dunedan This is your code, do you have an idea?

**Comment by Dunedan** [comment]
So for reference this is what `pylint` reports:
```
simplemma/strategies/fallback/lemmatization_fallback_strategy.py:1:0: R0401: Cyclic import (simplemma -> simplemma.lemmatizer -> simplemma.strategies -> simplemma.strategies.dictionaries -> simplemma.strategies.dictionaries.trie_directory_factory) (cyclic-import)
simplemma/strategies/fallback/lemmatization_fallback_strategy.py:1:0: R0401: Cyclic import (simplemma -> simplemma.language_detector -> simplemma.strategies -> simplemma.strategies.dictionaries -> simplemma.strategies.dictionaries.trie_directory_factory) (cyclic-import)
```

I'd probably just break the dependency cycle by moving the definition of the version number to another module like this:

```diff
diff --git a/simplemma/__init__.py b/simplemma/__init__.py
index bf94f83..2bf41cf 100644
--- a/simplemma/__init__.py
+++ b/simplemma/__init__.py
@@ -14,7 +14,6 @@ __title__ = "simplemma"
 __author__ = "Adrien Barbaresi, Juanjo Diaz and contributors"
 __email__ = "barbaresi@bbaw.de"
 __license__ = "MIT"
-__version__ = "1.1.1"
 
 
 from .language_detector import LanguageDetector, in_target_language, langdetect
@@ -26,3 +25,4 @@ from .token_sampler import (
     TokenSampler,
 )
 from .tokenizer import RegexTokenizer, Tokenizer, simple_tokenizer
+from .version import __version__
diff --git a/simplemma/strategies/dictionaries/trie_directory_factory.py b/simplemma/strategies/dictionaries/trie_directory_factory.py
index 8f534ca..8c0c9a3 100644
--- a/simplemma/strategies/dictionaries/trie_directory_factory.py
+++ b/simplemma/strategies/dictionaries/trie_directory_factory.py
@@ -14,7 +14,7 @@ except ImportError:
             raise ImportError("marisa_trie and platformdirs packages not installed")
 
 
-from simplemma import __version__ as SIMPLEMMA_VERSION
+from simplemma.version import __version__ as SIMPLEMMA_VERSION
 from simplemma.strategies.dictionaries.dictionary_factory import (
     DefaultDictionaryFactory,
     DictionaryFactory,
diff --git a/simplemma/version.py b/simplemma/version.py
new file mode 100644
index 0000000..a82b376
--- /dev/null
+++ b/simplemma/version.py
@@ -0,0 +1 @@
+__version__ = "1.1.1"
```

**Comment by adbar** [comment]
Thanks, that would work as a first step.

@juanjoDiaz Do you want to make a draft to improve on the current caching model or should we implement the short solution before anything else?
