### ISSUE TITLE
in_target_language can return ratios above 1.0 (again)

### ISSUE THREAD

**Issue by osma** [adbar/simplemma#149]
Bug #112 seems to have resurfaced. Again, `in_target_language('It was a true gift', lang=('en','de'))` returns 1.6666... in simplemma 1.1.1.

Looking at the code for `proportion_in_target_languages`, it was changed back to the [buggy algorithm](https://github.com/adbar/simplemma/commit/6586bcb389571a1b9b9a7b43dd8a238dd9656b9c#diff-3d9b26cb1f0cb05a8aa25538052fdc1629e74a04405d432d39cf5d7849f43fb7) that uses `sum()` in #116 (by @juanjoDiaz) and the unit test guarding against this bug was simply [removed](https://github.com/adbar/simplemma/commit/6586bcb389571a1b9b9a7b43dd8a238dd9656b9c#diff-615c74a5aa69e25288b38f719352db39c98a0e3e83c938ea0498c9882465c9ae) in the same PR :(

**Comment by adbar** [comment]
@osma Thank you for reporting the issue, this one slipped through.
