### ISSUE TITLE
English lemmatize returns funny nonsense lemma 'splitshine' for token 'e'

### ISSUE THREAD

**Issue by bartdpt** [adbar/simplemma#16]
Probably not intended, but this comes up with the current version  0.8.0

>>> import simplemma
>>> simplemma.lemmatize("e", "en")
'spitshine'

BR,
Bart Depoortere

**Comment by adbar** [comment]
@bartdpt Thanks for reporting the error! It's definitely a bug.

**Comment by adbar** [comment]
The problem is now solved, I will issue a new release soon. Thanks again @bartdpt!
