### ISSUE TITLE
ZeroDivisionError in in_target_language

### ISSUE THREAD

**Issue by osma** [adbar/simplemma#18]
Hello,

while testing Simplemma language detection in Annif (see https://github.com/NatLibFi/Annif/pull/626), I stumbled on a ZeroDivisionError when calling `in_target_language`. It's pretty easy to trigger for example by passing an empty string:

```python
>>> from simplemma.langdetect import in_target_language
>>> in_target_language('', lang='en')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oisuomin/.cache/pypoetry/virtualenvs/annif-3KgT0m3n-py3.8/lib/python3.8/site-packages/simplemma/langdetect.py", line 54, in in_target_language
    return in_target / total
ZeroDivisionError: division by zero
```

Other inputs can trigger this as well, for example any string that consists of only punctuation and/or spaces.

I can work around this in the calling code but I think it would be worth fixing in Simplemma itself.

**Comment by adbar** [comment]
Hi @osma, thanks for reporting the issue, I'll work on a fix.
