### ISSUE TITLE
Language detector can be tricked

### ISSUE THREAD

**Issue by osma** [adbar/simplemma#21]
I'm not sure if this is even worth reporting, but I was looking closer at how the language detection works and I realized that for languages that have [rules](https://github.com/adbar/simplemma/blob/main/simplemma/rules.py) (English and German currently), it can be quite easily tricked to accept nonsensical input and respond with high confidence that it is English (or probably German):

```python
>>> from simplemma.langdetect import in_target_language, lang_detector
>>> in_target_language('grxlries cnwated pltdoms', lang='en')
1.0
>>> lang_detector('grxlries cnwated pltdoms', lang=('en','sv','de','fr','es'))
[('en', 1.0), ('unk', 0.0), ('sv', 0.0), ('de', 0.0), ('fr', 0.0), ('es', 0.0)]
```

This happens because the English language rules match the word suffixes (in this case, `-ries`, `-ated` and `-doms`) in the input words without looking too carefully at the preceding characters (the word length matters though).

This is unlikely to happen with real world text inputs, but it's possible for an attacker to deliberately trick the detector.

**Comment by adbar** [comment]
Hi @osma, good point! As you say I'm not sure what to make of it, I'll leave the issue open for now.

**Comment by GrazingScientist** [comment]
Hi @osma ,

although currently I cannot forsee the consequences of you finding, I really appreciate it that you reported it! Thank you! :smiley:
