### ISSUE TITLE
Czech tokenizer is very slow

### ISSUE THREAD

**Issue by erip** [adbar/simplemma#22]
Thanks for this great tool! I'm using it to align English lemmas with Czech lemmas for an MT use case. I'm finding that while the English lemmatizer is extremely fast (haven't benchmarked, but your ~250k/s estimate seems reasonably close), Czech is quite slow.

A tiny microbenchmark (admittedly misleading) shows disparity between the two:

```python
In [1]: from simplemma import lemmatize

In [2]: %timeit -n1 lemmatize("fanoušků", lang="cs")
The slowest run took 768524.54 times longer than the fastest. This could mean that an intermediate result is being cached.
27.6 ms ± 67.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]: %timeit -n1 lemmatize("banks", lang="en")
The slowest run took 464802.09 times longer than the fastest. This could mean that an intermediate result is being cached.
16.9 ms ± 41.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

I see that lemmas are cached in the source code, with a single loop we see a near double penalty for Czech over English. I'm not exactly sure how to improve this immediately so I'm reporting it here for awareness and for others. 😄

**Comment by adbar** [comment]
Hi @erip, thanks for your feedback!
The data first need to be loaded, as the vocabulary file for Czech is larger my guess is that you're mostly measuring this difference.

Data corresponding to a language code should be cached between calls, so you could call the `lemmatize` function first and then the timing function. Please report on the results if you notice a change.

**Comment by erip** [comment]
Thanks, @adbar. Totally appreciate that this is sketchy. I'm definitely finding a bottleneck in my code. I'll try to get some example data here soon.

**Comment by adbar** [comment]
@erip Do you have anything to share?
