### ISSUE TITLE
Language tags are not always from ISO 639-1

### ISSUE THREAD

**Issue by osma** [adbar/simplemma#30]
This may be nitpicking, but here goes.

The top level [README](https://github.com/adbar/simplemma#supported-languages) states:

> The following languages are available using their [ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes):

But this isn't true in all cases. Currently supported three letter codes `enm` (Middle English) and `hbs` (Serbo-Croatian) are not from ISO 639-1 but from ISO 639-3.

Should this be changed to refer to [IETF BCP 47 language tags](https://en.wikipedia.org/wiki/IETF_language_tag) instead? A downside is that the Wikipedia page only lists some of the more common languages (for understandable reasons, since there are so many valid codes). In particular, Middle English and Serbo-Croatian are not listed there.

**Comment by osma** [comment]
Personally, I think BCP 47, in all its ugliness (basically "use a two-letter ISO 639-1 code if it exists, otherwise you can use ISO 639-2, ISO 639-3 or ISO 639-5 three-letter codes"), is the more relevant language code system for the use cases that I can think of. That's what most of the Internet uses for language identification (HTTP, HTML, XML, RDF...) and although it's not mentioned in the README, it seems to me that Simplemma has been following it so far.

**Comment by adbar** [comment]
I see, it's a documentation issue after all. What I use is ISO 639-1 + ISO 639-3 if something doesn't fit. Maybe I could just explain it like this but I'm glad to learn there is BCP 47 for that as well!
