### ISSUE TITLE
Two odd lemmatizations in Dutch language version

### ISSUE THREAD

**Issue by aartbastiaan** [adbar/simplemma#31]
Hello,

I found two odd lemmatization errors in the Dutch language version.

1. The Dutch singular noun 'meter' ("meter") is lemmatized as 'peter' (rare word for "godparent") when it should just be 'meter'. The plural form 'meters' however does get correctly lemmatized as 'meter'. See picture below.
2. A word consisting of simply the letter 'n' gets incorrectly lemmatized as 'kinnesinne', a very rare word that apparently means "jealousy". The actual lemma of 'n' would be the indefinite article 'een' (or, alternatively, just 'n').

![simpl](https://user-images.githubusercontent.com/57894235/211558351-2b436b33-667b-461b-9e07-27ce64359265.PNG)

Are these bugs within simplemma or should I report them to the dependency?

**Comment by adbar** [comment]
Hi @aartbastiaan, thanks for your feedback! Although I try to filter odd word pairs in the input data a few errors may slip through.
I can handle both errors and try to minimize similar cases in the future. If you have any more mistakes like "meter → peter" to share I'd be glad to hear about it.
