### ISSUE TITLE
Distributing the data in a json format

### ISSUE THREAD

**Issue by 1over137** [adbar/simplemma#32]
It would be great to distribute the data in a json format instead of using Python-specific `pickle`. The performance difference is pretty insignificant, provided the json is not encoded in ASCII escapes (but even then only about 2x):
```
In [18]: %%timeit
    ...: with lzma.open("ru.plzma") as f:
    ...:     lem = pickle.load(f)
    ...: 
117 ms ± 229 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [19]: %%timeit
    ...: with lzma.open("ru.json.lzma", 'rt') as f:
    ...:     lem = json.load(f)
    ...: 
120 ms ± 2.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

```
This would make it much easier to reuse the data you've collected in this project.

**Comment by adbar** [comment]
Hi @1over137, I'm not primarily interested in making the data available, for a growing number of languages the data goes along with a series of rules and a search algorithm. Data alone cannot perform that well.

Also, as you show above it's already clear how to load the data to reuse it, I see not further need at this point but thanks for your feedback.
