### ISSUE TITLE
Replace lru_cache decorators by freely configurable alternative

### ISSUE THREAD

**Issue by adbar** [adbar/simplemma#43]
The LRU caches are currently used by the functions `_levenshtein_dist()` and `lemmatize()`.

Problem description:
1. So far their maximum sizes cannot be set by the user.
2. The LRU decorator also stands in the way of further function use, e.g. in a class or in another application.
3. There is no function directly available to the users which allows for clearing the caches (apart from `function_name.cache_clear()`)

See also these comments for reference:
- https://github.com/adbar/simplemma/pull/38#issuecomment-1401780261
- https://github.com/adbar/simplemma/pull/38#issuecomment-1402420705
- https://github.com/adbar/simplemma/pull/42#discussion_r1085853608

**Comment by adbar** [comment]
A possible solution, wrap the function in another instead of using a decorator:

```
from functools import lru_cache
cached_levenshtein_dist = lru_cache(maxsize=65536)(_levenshtein_dist)
```

- Advantages: removes cache-linked roadblock on function `_levenshtein_dist`, only one line of code
- Drawbacks: no way to set cache size (a `settings.cfg` mecanism is imaginable)

**Comment by juanjoDiaz** [comment]
How is the function different than the decorator?

This doesn't solve the problem of having `_levenshtein_dist` in other internal methods and doesn't solve the problem of controlling the cache size.

**Comment by adbar** [comment]
The cache for the Levenshtein distance wasn't necessary, it's hardly used during dictionary construction and during lemmatization it's a cache within a cache, so I deleted it, one problem less.

@juanjoDiaz Now there's only the cache around `_lemmatize()` left. It's marginally better since it's clearly isolated. The main point is that you can now choose to wrap your own class around `_lemmatize()` or `_return_lemma()` without being hindered by this cache.

**Comment by adbar** [comment]
@juanjoDiaz Do you still have improvements in mind concerning this issue or is it now solved?
