### ISSUE TITLE
Use require.txt for dependencies and dev dependencies

### ISSUE THREAD

**Issue by juanjoDiaz** [adbar/simplemma#51]
I think that this is a must to ensure that other people can easily get the library on their local.

At the moment there is no prod dependencies so that's not a concern.

**Comment by osma** [comment]
Isn't it enough to have the dependencies declared in `setup.py` ? Simplemma is a library, not an end user application. Tools like setuptools and pip are able to pick up those dependencies from setup.py.

Of course it would be possible to switch to a smarter dependency management tool such as Poetry, and/or a more modern declaration of dependencies like `pyproject.toml` (PEP 518, supported by e.g. Poetry).

**Comment by adbar** [comment]
The good thing is that there are no required dependencies.

The requirements for tests and evaluation could be supplied in a separate file, in the future I would support a move towards PEP 518 if this solution becomes prevalent.
