### ISSUE TITLE
Checking the behavior of dictionary_factory

### ISSUE THREAD

**Issue by adbar** [adbar/simplemma#56]
Hi @juanjoDiaz,

I'm wondering if this line in the dictionary factory you recently wrote could mean the data is emptied systematically?
https://github.com/adbar/simplemma/blob/1f3707bec868ec3e5ec8165b1b7e5e1539118f15/simplemma/dictionary_factory.py#L50

The lines after that aren't completely clear to me either (e.g. why `lang for lang in self._data` where `self._data.keys()` is used above).

It turns out that loading a single dictionary using the new method inflicts a penalty of about 0.3 sec on my computer, I'm not sure why (source: [pyinstrument](https://github.com/joerick/pyinstrument)).
I'm aware that the LRU cache in the factory should be beneficial overall, I just want to check the code.

**Comment by adbar** [comment]
I let it slip through then, I guess it's either `self._data = {}` or the `self._data.pop(lang)` logic, right now both of them are in use.

**Comment by adbar** [comment]
Yes, like you just corrected :heavy_check_mark:

**Comment by adbar** [comment]
But then this line is superfluous as `_data`should be empty?
`for lang in [lang for lang in langs if lang not in self._data]:`

**Comment by juanjoDiaz** [comment]
🤦‍♂️ indeed
Fixed

**Comment by adbar** [comment]
That's better with the speed, the difference relatively to version 0.9.1 is now minimal, we can leave the issue closed.
