### ISSUE TITLE
Create configurable Rules Engine

### ISSUE THREAD

**Issue by juanjoDiaz** [adbar/simplemma#63]
At the moment we have many rules:

* Simple rules (mainly ending substitutions)
* A quite complex rule system for German
* A rule to decomposed words split by hyphens
* Known prefix recognition for German & Russian
* Affix search used to try identify works skipping the beginning or end of the word (not 100% sure of how this works)
* Greedy search (not sure what this does)

It would be great to have a configurable rule engine.
All this rules can be there as default rules that can be enabled/disabled & users can also add their own rules.

**Comment by juanjoDiaz** [comment]
Thinking more of this...

`en`, `fi`, `nl`, `pl` and `ru` rules are all suffix substitutions with some rules are not being applied if the word doesn't have a minimum length

Where are those length exclusion coming from?
I would help standardizing rules if we just have a minimum word length per language. So it's easy to standardize the rules.

`de`, however, is quite complex. It has different rules for uppercase tokens and for greedy vs non-greedy search. Also the `NOUN_ENDINGS_DE` rules seems a bit complex.

Could we simplify this be more in line with the other languages do?

**Comment by adbar** [comment]
The word length exclusion reduces the impact of the rules in case they are way off: longer words are usually less frequent (so faulty rules will be less apparent) and they are more likely not to be in the dictionary.

I'm working on making the German rules lighter, they are too complex for what they bring.
