### ISSUE TITLE
Returning lowercase token for non found tokens might be incorrect

### ISSUE THREAD

**Issue by juanjoDiaz** [adbar/simplemma#83]
Hi @adbar ,

Working on the code I notice this test:
```python
    text = "Pepa e Iván son una pareja sentimental, ambos dedicados al doblaje de películas."
    assert (simplemma.text_lemmatizer(text, lang="es", greedy=False)) == [
        "pepa",
        "e",
        "iván",
```
https://github.com/adbar/simplemma/blob/main/tests/test_lemmatizer.py#L143-L147

this seem incorrect.
Pepa and Iván are first names and, as such, they should be capitalized.

There is some logic in the lemmatizer that lowercase the tokens for some languages:
```python
BETTER_LOWER = {"bg", "es", "hy", "lt", "lv", "pt", "sk", "uk"}

#...

 return token.lower() if next(iter(dictionaries)) in BETTER_LOWER else token
```
https://github.com/adbar/simplemma/blob/main/simplemma/lemmatizer.py#L303

Why is that logic there?
Should we respect capitalization?
Should we include common names in the dictionaries?
How could we improve this?

**Comment by juanjoDiaz** [comment]
It make sense.
Let's get my PR about "strategies" merged and then we can add this as a configurable strategy or something like that

**Comment by adbar** [comment]
That sounds good.
